apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
    type: front-tier
  name: result
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: 8081
    targetPort: 80
    nodePort: 31001
  selector:
    app: result
    type: front-tier
